# Generated by Django 5.2.5 on 2025-09-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='usuario',
            field=models.CharField(default='anônimo', max_length=200),
        ),
    ]
