# Generated by Django 5.2.5 on 2025-09-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_resposta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='data_criacao',
            field=models.DateTimeField(default='anônimo', max_length=200),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='votos',
            field=models.IntegerField(default=0),
        ),
    ]
